### ISSUE TITLE
Errors in all your coding - on website, formvalidator, fg_membersite

### ISSUE THREAD

**Issue by QuantumField** [simfatic/RegistrationForm#13]
I know you are trying hard and your registration form is a great concept... however you have multiple errors through out you Html Form Guide website and your include scripts fg_membersite.php and formvalidator.php.

Firstly in reference to your website........
http://www.html-form-guide.com/php-form/php-registration-form.html

ERROR 1 - under the heading "The database table structure"................
function CreateTable()
{
       $qry = "Create Table $this->tablename (".
            "id_user INT NOT NULL AUTO_INCREMENT ,".
            "name VARCHAR( 128 ) NOT NULL ,".
            "email VARCHAR( 64 ) NOT NULL ,".
            "phone_number VARCHAR( 16 ) NOT NULL ,".      ??????????????
           etc etc

why is phone_number in Create Table when under the heading "Inserting the registration to the table"  you have ........
    $insert_query = 'insert into '.$this->tablename.'(
           name,
            email,
            username,
            password,
            confirmcode
            )
            values
            (
            "' . $this->SanitizeForSQL($formvars['name']) . '",
            "' . $this->SanitizeForSQL($formvars['email']) . '",
            "' . $this->SanitizeForSQL($formvars['username']) . '",
            "' . md5($formvars['password']) . '",
            "' . $confirmcode . '"
            )';  
Question: where is the phone number going to be inserted... OBVIOUSLY nowhere!
This code will insert the username data into the phone number field in the Created TABLE... thats if you know how SQL works... sequential inputs dude!!
This coding will output data in wrong fields in your MySQL database... so maybe have a look at that.
Also under the heading "The registration form"......
you dont even have a phone field in your form to input your phone number?????

ERROR 2 - your SQL syntax is shockingly coded in fg_membersite.php......
anywhere there is  $qry .... you have inconsistent coding with uppercase and lowercase  operators...
For example... operators such as Update - set - where - and - from.............
SHOULD BE UPPERCASE CONSISTENTLY LIKE SO......
Example Update should be UPDATE,  Set should be SET, Where should be WHERE, from should be FROM and and should be AND.....

ERROR 3 - Online 103 in fg_membersite.php......
Should there be a space before and after the operand  ||  .. or should there Not be a any spaces???
your code ...... if(empty($_GET['code'])||strlen($_GET['code'])<=10)...................
should be .......if(empty($_GET['code']) || strlen($_GET['code']) <=10)
because line 756 shows similar coding... however once again inconsistent,
......................if(!$result || mysql_num_rows($result) <= 0)
SO QUESTION... what is the right way of doing such coding...
Should there BE or should there NOT be a any spaces??????

ERROR 4 - Online 806 in fg_membersite.php......there are spaces once again... should there BE or NOT be spaces......
your code ......  if(!mysql_query( $insert_query ,$this->connection))
should be ....... if(!mysql_query($insert_query,$this->connection))

ERROR 5 - Confirmuser "code" is buggy....  you have multiple instances refering to confirmcode in a lot of different places... sometimes the database will put a 'y' in the confirmcode field or will put the 32 full characters code into the field... this causes problems for users logging in and also not receiving their confirmation emails.... if they dont get their  confirmation emails and click the confirm link they will not be able to log on...   if the database does put the UPDATE and SET confirmcode='y'  the form works brilliantly... however once again if it puts in the long confirm code then the whole script is stuffed!!
I recommend  maybe looking at a different way of coding and confirming the new user registrant.

ERROR 6 - throughout Formvalidator.php ..... inconsistent coding... for example...
you have $bret=true   and   $bret = true  everywhere throughout code......
you have $bret=false   and   $bret = false  everywhere throughout code......

on lines 261,265, 276 for example and lines 376, 378, 455, 464, 487, 497  coding is spread over multiple lines.................
should have whatever in the brackets included all on the one line..... with parentheses doing that is ok...however...wait theres more....
on line 205 there is NO $max_len  next to $variable_name  like you have with min_len on line 220

ERROR 7 - most of your html and php pages that come with the script have inconsistent coding as well.... for example single and double quotes throughout your HTML code... Upper and lowercase attributes... should validate your webpages at w3c before posting to be downloadable...

ERROR 8 - all webpages are not HTML5 compliant and Mobile freindly.. you have to change all the head code and meta tags etc

ERROR 9 - CSS conflicts - If someone wants to implement these webpages in a Bootstrap environment they will have to change the container class in the  fg_membersite.css file.
In change-pwd.php  ....   login.php ....  confirm.php  and reset-pwd-req.php for example you have 
     < div class="container" >  ........ wrapping the form inputs.
The ID reference to the class you have in the css file ( #fg_membersite .container) conflicts with Bootstraps container class. Form input fields will expand to 100% of the page etc., basically stuffing up the form layout etc.
The fix for that is to just change the container class in the fg_membersite.css file..
Change ........  #fg_membersite .container
to .................. #fg_membersite .containernewword
so change all the div fields in the html and php webpages ....
change 
      < div class="container" >
to 
     < div class="containernewword" >
no more conflicts with Bootstrap CSS.container class.
(Dont change the bootstrap container code in their framework or webpages... just the ones wrapping the form fields in change-pwd.php etc etc from HTML FORM Guide).

Looking at your forum postings in both register form and form validator there seems to be nothing but problems with all the users downloading your scripts..... from deprecated code to basic not receiving certain info or PHP notices Undefining scripts..... as you most probably know with JavaScript there are things like JShint that recommends to fix code and tidy up the code....
Im not sure if there is a PHP complier that will check PHP code syntax errors etc.... but now i am looking for one so i can run it against code that people like yourself put up online to test to see if whether to implement someone else's buggy coding on my website.

Recommend to validate all of your script and pages before making them downloadable or getting people to buy your Simfactic form builder... have a nice day!

**Comment by daddymac72** [comment]
Helllo, did you have any suggestions for this error you mention? My users seem to be randomly NOT receiving the confirmation emails and you seem to be on to something here but i'm not sure I follow what you say is the problem?

ERROR 5 - Confirmuser "code" is buggy.... you have multiple instances refering to confirmcode in a lot of different places... sometimes the database will put a 'y' in the confirmcode field or will put the 32 full characters code into the field... this causes problems for users logging in and also not receiving their confirmation emails.... if they dont get their confirmation emails and click the confirm link they will not be able to log on... if the database does put the UPDATE and SET confirmcode='y' the form works brilliantly... however once again if it puts in the long confirm code then the whole script is stuffed!!
 I recommend maybe looking at a different way of coding and confirming the new user registrant.

**Comment by QuantumField** [comment]
Firstly..... the initial downloadable code is buggy..... sloppy programming... however it is a good script once it is cleaned up so to speak.... if you follow all my findings in what I posted that would be a good starting point....

Secondly..... currently at the time of writing this reply there are 8 Issues ..... when you click on the Issues 8 link...there are 3 closed issues as well....   check out the one that Kayoti commented on Jul 21, 2013....  confirmation email #4...... I did have that problem as well which I couldn't work out for a while... i was getting double slashes // ..... so i think he has got the fix.... just change the URl  (small l)  to URL .... (capital L)

Thirdly...... in respect of .... My users seem to be randomly NOT receiving the confirmation emails .... had that problem all the time... please look at the code in fg-membersite.php .... a lot of code I know.... anyway look for  confirmcode... about 3 places or spots in the full code..... look for SET confirmcode=y   and UPDATE confirmcode.....  make sure that the SQL  is changed to what I recommended in Error 2 that I listed above.... hopefully with Kayotis fix and changing the SQL to proper statements should work...
however.....

In respect of my comment Error 5.... For some reason when the users submitted the form.... the database and the form field where the Y (in database SET  or  Update confirmcode=y) was supposed to be implanted would  be hashed like a 32 bit MD5 password... i dont know why this was happening but i think its the sloppy coding of inconsistent SQL statements... upper and lowercase.... what I did was that I changed the Y to a yes and all the SQL statements to be in uppercase..... it seems to be inserting the yes into the database correctly.... because when it doesnt.... for example it puts in a 32 bit hashed code (eg... jdud7e3hdsndbcgxctsdghwshweydbdx   whatever into the formfield of the database) ... meaning that the code cannot respond to the database formfield correctly (Y or Yes) and therefore cannot send the confirmation email link to the new user... and therefore the new User cannot confirm... therefore he/she cannot log in.....


Another thing could be that the server you are hosting on may have been upgraded to MySQLI (improved) and the code we are using in just plain old MySQL...

anyway I gotta go and haven't got time for this ..... try doing what I suggested in all my error comments above (especially if you are using Bootstrap) and valdate your webpages at W3C  etc.., and you should be fine.... have a great day!!

**Comment by daddymac72** [comment]
thanks for the response! it looks like the one issue has since been addressed and updated because I don't see the code like that issue describes and the link works fine for me.
