### ISSUE TITLE
Password Security

### ISSUE THREAD

**Issue by Rawrishly** [simfatic/RegistrationForm#14]
I noticed you made an update to password security, however it's nowhere near as secure as it should be. You should be using something meant for password hashing, like PBKDF2, rather than doing some random combination of salting, md5, and sha1. The point of using something meant for password hashing is so that it takes a long time to calculate the hashes. Here's a php script that has everything you need, https://crackstation.net/source/password-hashing/PasswordHash.php and a tutorial explaining general password security and the reasoning behind each part https://crackstation.net/hashing-security.htm

**Comment by Firestorm-Graphics** [comment]
+ 1 on that

**Comment by davidberriman** [comment]
I have created a new form registration project which is built on this one which improves many of the security issues : https://github.com/davidberriman/form_registration

**Comment by prasanthmj** [comment]
Fixed the issue
