### ISSUE TITLE
Please Help Me

### ISSUE THREAD

**Issue by nickellawrence** [simfatic/RegistrationForm#17]
I am getting the above error whenever I try to run any form and my database login and password is correct.

Warning: mysql_connect() [function.mysql-connect]: Access denied for user 'a2211478_admin'@'localhost' (using password: YES) in /home/a2211478/public_html/registration_files/include/fg_membersite.php on line 773

see here for your self: http://mybitreturns.net23.net/registration_files/index.html

please send replies to E-Mail: badbreedrebel@outlook.com

**Comment by davidberriman** [comment]
That's a standard MySQL message... it looks like you don't have the correct password set in your membersite_config.php file
