### ISSUE TITLE
I want to display user id into code ....

### ISSUE THREAD

**Issue by ashishkumar2016** [simfatic/RegistrationForm#19]
thank you in advance..
please help me about it , i want to display user id in code for display userprofile picture
so how to get user id..

**Comment by raph-tr** [comment]
hi there, same question here : i tried to play around in your controlers, fg_membersite and login files but could not find a clean way to have users id as a session variable, which would help me a lot !!!

i noticed there are but few answers to issues on this github, is this project still alive ??

**Comment by raph-tr** [comment]
in case someone is interested, a fix was described here : [https://github.com/davidberriman/form_registration/issues/4](https://github.com/davidberriman/form_registration/issues/4)
