### ISSUE TITLE
Using the forms in wordpress

### ISSUE THREAD

**Issue by josat57** [simfatic/RegistrationForm#26]
Hi Nice Job, Actually I am new to php, however I downloaded the files and try to use it with wordpress all errors I have been able to correct but when I test the register it automatically redirects me to index.php without creating the user.
Meanwhile if I try it without wordpress it works but emails are not sent and also login does not work.

May be you have Ideas on how to make this work. especially on wordpress,

Thanks.

**Comment by prasanthmj** [comment]
Wordpress has its own login and signup. The way to modify Wordpress is through plugins. Read up about Wordpress plugins
