### ISSUE TITLE
Error when registering

### ISSUE THREAD

**Issue by cwild1** [simfatic/RegistrationForm#28]
I am getting the below error message when I try to submit the register form for the 1st time. Any ideas?

<img width="1365" alt="screen shot 2018-06-24 at 7 37 34 pm" src="https://user-images.githubusercontent.com/9712014/41824906-13643808-77e6-11e8-99ba-61b2beada9e5.png">

**Comment by prasanthmj** [comment]
You don't have mysql extensions installed on your server. 
Solutions:
https://stackoverflow.com/a/13825423/9728797

**Comment by cwild1** [comment]
mySQL is installed on my server

*. . .*

*Christopher Wilder*

Information Technology Director / Graphic Designer

M 803.272.2556

*Chick-fil-A Camden *

2211 W. Dekalb Street, Camden, SC 29020

*Chick-fil-A Rivers Avenue*

7616 Rivers Avenue, North Charleston, SC 29406

**Comment by cwild1** [comment]
I found out what it was... My server was running SQL 7.2 and apparently
part of your code was depreciated in 5.5? Any ideas on how to get it
working on 7.0+ ?

*. . .*

*Christopher Wilder*

Information Technology Director / Graphic Designer

M 803.272.2556

*Chick-fil-A Camden *

2211 W. Dekalb Street, Camden, SC 29020

*Chick-fil-A Rivers Avenue*

7616 Rivers Avenue, North Charleston, SC 29406
