### ISSUE TITLE
Registration is not working

### ISSUE THREAD

**Issue by MegaGamerUnlimited** [simfatic/RegistrationForm#29]
After I try registrating it says 
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /storage/ssd1/349/9719349/public_html/RegistrationForm-master/RegistrationForm-master/source/include/fg_membersite.php:773 Stack trace: #0 /storage/ssd1/349/9719349/public_html/RegistrationForm-master/RegistrationForm-master/source/include/fg_membersite.php(729): FGMembersite->DBLogin() #1 /storage/ssd1/349/9719349/public_html/RegistrationForm-master/RegistrationForm-master/source/include/fg_membersite.php(86): FGMembersite->SaveToDatabase(Array) #2 /storage/ssd1/349/9719349/public_html/RegistrationForm-master/RegistrationForm-master/source/register.php(6): FGMembersite->RegisterUser() #3 {main} thrown in /storage/ssd1/349/9719349/public_html/RegistrationForm-master/RegistrationForm-master/source/include/fg_membersite.php on line 773

**Comment by openbah** [comment]
It is because mysql_* functions were completely removed from PHP 7. You must update the code in order to use it with PHP 7.
