### ISSUE TITLE
Error shown while resetting password (line 411)

### ISSUE THREAD

**Issue by redcrayon** [simfatic/RegistrationForm#3]
Selecting forgot password ---> email sent successful.
Clicking on email confirmation link ---> the following is displayed:

---

Warning: uniqid() expects at least 1 parameter, 0 given in /home/content/s/l/a/slanguilla/html/ProofingPlace/registration/source/include/fg_membersite.php on line 411

Password is Reset Successfully
Your new password is sent to your email address.

----- end -----

line 411:
$new_password = substr(md5(uniqid()),0,10);

change to:
$new_password = substr(md5(uniqid(rand())),0,10);

**Comment by ghigio2000** [comment]
Hi,
registration with email confirmation works great.
But when I try to use the Forgot Password then the email is not sent.
I put my email into the "membersite_config.php" as well as into the "fg_membersite.php".

Any suggestion is appreciated, best regards.
Giorgio

**Comment by prasanthmj** [comment]
Closing old issues
