### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by miadmmam** [simfatic/RegistrationForm#30]
I was trying to use this code with my mongoDB and got an error:

Fatal error: Call to undefined function MongoClient_connect() in /var/www/html/include/fg_membersite.php on line 733

I wondered if there is a version of this RegistrationForm for MongoDB or if anyone can help me change it from mysql to mongo.

**Comment by prasanthmj** [comment]
The code supports only MySQL at the moment

**Comment by miadmmam** [comment]
Any tips on how to change it from MySQL to MongoDB ?

**Comment by Birsker** [comment]
I have used your RegistrationForm for many years, but now it no longer works because mysql is updated to mysqli on the server i use....I hope you can help me ...

**Comment by Birsker** [comment]
I have used your RegistrationForm for many years, but now it no longer works because mysql is updated to mysqli on the server i use....I hope you can help me ...

**Comment by prasanthmj** [comment]
There is no support for mongodb at the moment
