### ISSUE TITLE
This code is not working with PHP 7.3

### ISSUE THREAD

**Issue by 39edivad** [simfatic/RegistrationForm#33]
Hi there bluehost has updated to php 7.3 and now my website is broken. 
Please can you tell me if your php code is compatible with php 7.3? If not, what should I do to make it compatible?
Thank you in advance!!! 
P.S. I really really appreciate and love your registration form code!!!

**Comment by prasanthmj** [comment]
>>now my website is broken
What is the error that you are getting?

**Comment by 39edivad** [comment]
First of all, T HA N K   Y O U  for getting back to me!!!!!!!!!!!!!!!!
I'm not having an error but it seems it can find a match in the database. 
I had the old version installed, the one I downloaded years ago from the website HTML.form.guide 
I think the problem is the password check. The old version used md5 hash function. To be sure I've tried to create a new user but even accessing the new user it doesn't work. I would really like to fix it as soon as possible to pass to php 7.3. Do you have any hint?

**Comment by 39edivad** [comment]
Ok I think I have an hint. 
It fails to the password verification at the following line into CheckLoginInDB($username,$password) function:
if(!password_verify($password , $row['password'] ))
        {
            it arrives here everytime. So how can I be sureI'm comparing the password with the hashed password?
         }

I look forward to hearing from you. 
THANKS IN ADVANCE!!!!!!!!!!

Davide

**Comment by 39edivad** [comment]
I've seen other peopla are having with their php code issues using password_verify that seems it's not hashing the user password before to compare it with the hashed version in the database. Please let me know what I'm doing wrong with your code.

**Comment by 39edivad** [comment]
I've just got what the problem was!!! It's not your code but the fact that my database was created with the old php code so the password were 32 char long. 
I've now updated to 255 char so now they match correctly. ANYWAY I want to thank you so much for your wonderful work and for your generosity to give it for free!!! I'm just a video artist and it would have been impossible for me to pay someone to code the restricted area of my website! Please keep this code always updated!!!!!!!!!!!! ;) I wish you a wonderful week end and stay safe!!!
