### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by Salo6224** [simfatic/RegistrationForm#42]
In this assignment, you will create an enhanced registration form using HTML. The form should meet the basic requirements and include additional input types and features to make it a comprehensive user registration form. Your HTML code should follow the guidelines below and meet accessibility, validation, and organizational best practices.

Instructions

Basic Structure

Document Type Declaration

• Begin your HTML document with the correct document type
declaration (<!DOCTYPE html>).

HTML Structure

• Structure your document using the <html>,
<head>, and <body> tags.

Meta and Title

• Include a <meta charset="UTF-8"> tag for
character encoding.
• Add a meaningful <title> for the page (e.g.,
"User Registration Form").

External Stylesheet

• Link to an external stylesheet (styles.css) to style the
registration form, ensuring the link is correctly referenced within the
<head> section.

Heading and Introduction

• Create a prominent title for the form using a heading tag
(e.g., <h1> with "User Registration Form").
• Provide a brief introduction using a <p> tag,
instructing users to complete the required fields.

Form Elements and Structure

Form Element

• Use the <form> tag with the method attribute set to
post and the action attribute set to a placeholder value (e.g.,
"/submit").
• Assign an ID to the form for unique identification.

Fieldset and Labels

• Organize input fields within appropriate <fieldset>
tags for logical grouping.
• Each input field should be described with a <label>
element for clarity and accessibility.

Required Input Fields

• Text Input: Collect the user's First Name, Last Name, and
Email. Set the type to text or email, and mark each field as
required.
• Password Input: Create a password field that enforces at
At least one uppercase letter, one lowercase letter, one digit, and a minimum
length of 8 characters using the pattern attribute.
• Radio Buttons: Provide options for Personal Accounts and
Business Account under the account-type input.
• Checkbox: Include a checkbox for accepting the Terms and
Conditions with a link to the terms page.
• File Input: Allow the user to upload a Profile Picture with
an accept attribute for image files.
• Number Input: Add an Age input field with a range limit
between 18 and 120 years.
• Select Dropdown: Include a Referrer dropdown with options
for how the user found the site (e.g., friend, online search, social media).
• Textarea: Provide a Bio input area with multiple rows and
columns for the user to introduce themselves.

Additional Comprehensive Fields

Advanced Input Types

• Date Input: Collect the user’s date of birth using a date
type.
• Checkboxes for Multiple Interests: Create checkboxes for
Interests (e.g., coding, design, reading).
• Dropdown with Groups: Add a Country dropdown with regions
grouped by <optgroup>.
• Ensure that all fields are appropriately labelled and
formatted.

Submit Button
Submit Button

• Include a submit button (<button
type="submit">) at the bottom of the form.

Accessibility and Validation
HTML5 Validation

• Apply HTML5 attributes like required, pattern, min, max, and max length to enforce validation.

  
Submission Requirements  

• Submit the HTML file named YourFirstName-LastName.html.
• Include a screenshot of the rendered registration form, named YourFirstName-LastName.png.

**Comment by prasanthmj** [comment]
This is not an issue. create the issue in your own fork please
